/**
 * Preset skin catalog. Each skin is a registered `ThemeDefinition`: a base
 * color scheme plus alias-token overrides applied by the theme presenter as
 * inline CSS variables on body (values may be plain colors or rgba strings —
 * the presenter writes them verbatim). Swatch chrome colors live in
 * SkinRow.module.css; the token maps here are the theme values.
 */
import type { ThemeTokens } from '@deepseek-ai/dsh-client-ui-theme/client'
import type { SkinKey } from './client/locales.ts'

/** Registrable skin ids (built-in preference ids and `system` are reserved). */
export const SKIN_IDS = ['ocean', 'sakura', 'forest', 'midnight'] as const

/** One skin id from the catalog. */
export type SkinId = typeof SKIN_IDS[number]

/** One preset skin: theme registration data plus the row's label key. */
export interface SkinDefinition {
  /** Skin id (the setSkin/theme.setTheme argument). */
  id: SkinId
  /** Base palette this skin builds on; the presenter switches the dark body attribute from it. */
  colorScheme: 'light' | 'dark'
  /** Settings-row label key inside the `settings.skins` dictionary. */
  labelKey: SkinKey
  /** One-line description (documentation only). */
  description: string
  /** Alias-token overrides applied as inline CSS variables over the base palette. */
  tokens: ThemeTokens
}

/** All preset skins in picker order (registration order). */
export const SKINS: readonly SkinDefinition[] = [
  {
    id: 'ocean',
    colorScheme: 'light',
    labelKey: 'skins.ocean',
    description: '浅色蓝绿色系：海面蓝白底、深青色主色。',
    tokens: {
      '--dsw-alias-bg-base': '#eef3f9',
      '--dsw-alias-bg-layer-1': '#f6fafd',
      '--dsw-alias-bg-layer-2': '#edf3f9',
      '--dsw-alias-bg-layer-3': '#e3ecf5',
      '--dsw-alias-bg-overlay': '#f4f9fd',
      '--dsw-alias-bg-module-platform': '#e9f0f8',
      '--dsw-alias-border-l1': 'rgba(19, 47, 79, 0.08)',
      '--dsw-alias-border-l2': 'rgba(19, 47, 79, 0.14)',
      '--dsw-alias-border-l3': 'rgba(19, 47, 79, 0.18)',
      '--dsw-alias-label-primary': '#123049',
      '--dsw-alias-label-secondary': '#41607c',
      '--dsw-alias-label-tertiary': '#6b87a0',
      '--dsw-alias-label-caption': '#6b87a0',
      '--dsw-alias-label-dimmed': '#8fa6ba',
      '--dsw-alias-brand-primary': '#0e7490',
      '--dsw-alias-brand-text': '#0e7490',
      '--dsw-alias-button-primary-fill': '#0e7490',
      '--dsw-alias-button-primary-hover': '#155e75',
      '--dsw-alias-button-info-fill': '#0e7490',
      '--dsw-alias-button-info-hover': '#155e75',
      '--dsw-alias-state-business-primary': '#0e7490',
      '--dsw-alias-state-business-tertiary': '#cfe8f2',
      '--dsw-alias-state-success-primary': '#0f9d6e',
      '--dsw-alias-state-error-primary': '#d64545',
      '--dsw-alias-state-warn-primary': '#e08a00',
      '--dsw-specific-sidebar-fill': '#e6eef7',
      '--dsw-specific-sidebar-nav-item-active': '#dbe7f2',
      '--dsw-specific-sidebar-nav-item-hover': '#eef4fa',
      '--dsw-specific-sidebar-nav-item-active-accent': '#bcd9ea',
      '--dsw-specific-bubble': '#e3eef7',
      '--dsw-specific-bubble-highlight': '#d3e6f3',
      '--dsw-specific-input-major': '#f6fafd',
      '--dsw-specific-menu': '#e3ecf5',
      '--dsw-specific-selector': '#e9f0f8',
      '--dsw-specific-tip': '#eef4fa',
      '--dsw-alias-markdown-code-block': '#f1f6fb',
      '--dsw-alias-markdown-code-block-banner': '#e9f0f8',
      '--dsw-alias-markdown-inline-code': '#e3eef7',
      '--dsw-alias-scrollbar-bg-l1': '#d5dde6',
      '--dsw-alias-scrollbar-hover-l1': '#b9c4d0',
    },
  },
  {
    id: 'sakura',
    colorScheme: 'light',
    labelKey: 'skins.sakura',
    description: '浅色粉紫系：樱粉白底、玫红主色。',
    tokens: {
      '--dsw-alias-bg-base': '#fbf3f5',
      '--dsw-alias-bg-layer-1': '#fefafb',
      '--dsw-alias-bg-layer-2': '#f9eef1',
      '--dsw-alias-bg-layer-3': '#f5e6ea',
      '--dsw-alias-bg-overlay': '#fff8fa',
      '--dsw-alias-bg-module-platform': '#f7ebee',
      '--dsw-alias-border-l1': 'rgba(122, 41, 70, 0.08)',
      '--dsw-alias-border-l2': 'rgba(122, 41, 70, 0.14)',
      '--dsw-alias-border-l3': 'rgba(122, 41, 70, 0.18)',
      '--dsw-alias-label-primary': '#4a2c38',
      '--dsw-alias-label-secondary': '#7d5564',
      '--dsw-alias-label-tertiary': '#a27c89',
      '--dsw-alias-label-caption': '#a27c89',
      '--dsw-alias-label-dimmed': '#c0a1ac',
      '--dsw-alias-brand-primary': '#c2416c',
      '--dsw-alias-brand-text': '#c2416c',
      '--dsw-alias-button-primary-fill': '#c2416c',
      '--dsw-alias-button-primary-hover': '#a1335a',
      '--dsw-alias-button-info-fill': '#c2416c',
      '--dsw-alias-button-info-hover': '#a1335a',
      '--dsw-alias-state-business-primary': '#c2416c',
      '--dsw-alias-state-business-tertiary': '#f6dbe4',
      '--dsw-alias-state-success-primary': '#0f9d6e',
      '--dsw-alias-state-error-primary': '#d64545',
      '--dsw-alias-state-warn-primary': '#e08a00',
      '--dsw-specific-sidebar-fill': '#f7e9ed',
      '--dsw-specific-sidebar-nav-item-active': '#f3dfe6',
      '--dsw-specific-sidebar-nav-item-hover': '#fbeef2',
      '--dsw-specific-sidebar-nav-item-active-accent': '#ecc3d1',
      '--dsw-specific-bubble': '#fceef2',
      '--dsw-specific-bubble-highlight': '#f8dfe7',
      '--dsw-specific-input-major': '#fefafb',
      '--dsw-specific-menu': '#f5e6ea',
      '--dsw-specific-selector': '#f7ebee',
      '--dsw-specific-tip': '#fbeef2',
      '--dsw-alias-markdown-code-block': '#fcf2f5',
      '--dsw-alias-markdown-code-block-banner': '#f7e9ed',
      '--dsw-alias-markdown-inline-code': '#fceef2',
      '--dsw-alias-scrollbar-bg-l1': '#ecd9df',
      '--dsw-alias-scrollbar-hover-l1': '#dbbcc7',
    },
  },
  {
    id: 'forest',
    colorScheme: 'dark',
    labelKey: 'skins.forest',
    description: '深色松绿系：墨绿黑底、翠绿主色。',
    tokens: {
      '--dsw-alias-bg-base': '#0c1310',
      '--dsw-alias-bg-layer-1': '#111a15',
      '--dsw-alias-bg-layer-2': '#16221b',
      '--dsw-alias-bg-layer-3': '#1b2a21',
      '--dsw-alias-bg-overlay': '#223029',
      '--dsw-alias-bg-module-platform': '#1b2a21',
      '--dsw-alias-border-l1': 'rgba(255, 255, 255, 0.06)',
      '--dsw-alias-border-l2': 'rgba(255, 255, 255, 0.12)',
      '--dsw-alias-border-l3': 'rgba(255, 255, 255, 0.16)',
      '--dsw-alias-label-primary': '#e4efe7',
      '--dsw-alias-label-secondary': '#a8b8ad',
      '--dsw-alias-label-tertiary': '#85978b',
      '--dsw-alias-label-caption': '#85978b',
      '--dsw-alias-label-dimmed': '#6b7d71',
      '--dsw-alias-brand-primary': '#34d399',
      '--dsw-alias-brand-text': '#e4efe7',
      '--dsw-alias-button-primary-fill': '#34d399',
      '--dsw-alias-button-primary-hover': '#4ade80',
      '--dsw-alias-button-info-fill': '#34d399',
      '--dsw-alias-button-info-hover': '#4ade80',
      '--dsw-alias-state-business-primary': '#34d399',
      '--dsw-alias-state-business-tertiary': '#1b3a2c',
      '--dsw-alias-state-success-primary': '#34d399',
      '--dsw-alias-state-error-primary': '#f87171',
      '--dsw-alias-state-warn-primary': '#fbbf24',
      '--dsw-specific-sidebar-fill': '#0a100d',
      '--dsw-specific-sidebar-nav-item-active': '#1b2a21',
      '--dsw-specific-sidebar-nav-item-hover': '#131f18',
      '--dsw-specific-sidebar-nav-item-active-accent': '#20382b',
      '--dsw-specific-bubble': '#15201a',
      '--dsw-specific-bubble-highlight': '#1e3026',
      '--dsw-specific-input-major': '#16221b',
      '--dsw-specific-menu': '#1b2a21',
      '--dsw-specific-selector': '#1b2a21',
      '--dsw-specific-tip': '#16221b',
      '--dsw-alias-markdown-code-block': '#0f1813',
      '--dsw-alias-markdown-code-block-banner': '#131f18',
      '--dsw-alias-markdown-inline-code': '#1b2a21',
      '--dsw-alias-scrollbar-bg-l1': '#2a352e',
      '--dsw-alias-scrollbar-hover-l1': '#3b4a40',
    },
  },
  {
    id: 'midnight',
    colorScheme: 'dark',
    labelKey: 'skins.midnight',
    description: '深色紫蓝系：深空紫黑底、淡紫主色。',
    tokens: {
      '--dsw-alias-bg-base': '#0e0d19',
      '--dsw-alias-bg-layer-1': '#151322',
      '--dsw-alias-bg-layer-2': '#1b1930',
      '--dsw-alias-bg-layer-3': '#211e3a',
      '--dsw-alias-bg-overlay': '#2a2542',
      '--dsw-alias-bg-module-platform': '#211e3a',
      '--dsw-alias-border-l1': 'rgba(255, 255, 255, 0.07)',
      '--dsw-alias-border-l2': 'rgba(255, 255, 255, 0.13)',
      '--dsw-alias-border-l3': 'rgba(255, 255, 255, 0.18)',
      '--dsw-alias-label-primary': '#ece8f6',
      '--dsw-alias-label-secondary': '#b7b1cf',
      '--dsw-alias-label-tertiary': '#948db2',
      '--dsw-alias-label-caption': '#948db2',
      '--dsw-alias-label-dimmed': '#756e97',
      '--dsw-alias-brand-primary': '#a78bfa',
      '--dsw-alias-brand-text': '#ece8f6',
      '--dsw-alias-button-primary-fill': '#a78bfa',
      '--dsw-alias-button-primary-hover': '#8b5cf6',
      '--dsw-alias-button-info-fill': '#a78bfa',
      '--dsw-alias-button-info-hover': '#8b5cf6',
      '--dsw-alias-state-business-primary': '#a78bfa',
      '--dsw-alias-state-business-tertiary': '#2c2450',
      '--dsw-alias-state-success-primary': '#34d399',
      '--dsw-alias-state-error-primary': '#f87171',
      '--dsw-alias-state-warn-primary': '#fbbf24',
      '--dsw-specific-sidebar-fill': '#0b0a15',
      '--dsw-specific-sidebar-nav-item-active': '#211e3a',
      '--dsw-specific-sidebar-nav-item-hover': '#191627',
      '--dsw-specific-sidebar-nav-item-active-accent': '#352c5c',
      '--dsw-specific-bubble': '#1a1730',
      '--dsw-specific-bubble-highlight': '#262238',
      '--dsw-specific-input-major': '#1b1930',
      '--dsw-specific-menu': '#211e3a',
      '--dsw-specific-selector': '#211e3a',
      '--dsw-specific-tip': '#1b1930',
      '--dsw-alias-markdown-code-block': '#121021',
      '--dsw-alias-markdown-code-block-banner': '#191627',
      '--dsw-alias-markdown-inline-code': '#211e3a',
      '--dsw-alias-scrollbar-bg-l1': '#2a2642',
      '--dsw-alias-scrollbar-hover-l1': '#3b3557',
    },
  },
]
